### PR TITLE
tiltfile: pass TILT_HOST + TILT_PORT to local() commands

### LINKED ISSUE #4737: Invoking `tilt` from `local` breaks with custom port
### Expected Behavior
* Calling `local()` to shell out to Tilt (e.g. to interact with API) should work if Tilt was invoked with `tilt up --port=10351`

### Current Behavior
* No way to determine port to pass-through to `local()` call

### Steps to Reproduce

1. Add `local('%s get session Tiltfile' % (sys.executable,))` to `Tiltfile`
2. Ensure no instances of Tilt running on default port (10350)
3. Run `tilt up --port=10351` (or any non-standard port)

### Context
Per @nicks we already pass some extra environment variables through to `local()` calls and Tilt understands the `TILT_PORT` environment variable as-is, so the easiest solution for now is to just populate this explicitly.

### PR DESCRIPTION
**Pull request by milas**
Various Tilt extensions have been using `local()` to shell back
out to Tilt to use the API (e.g. `tilt apply -f ...`). This does
not play nice with custom ports if Tilt was invoked using the
`--port` argument.

Now, the current Tilt instance's port is passed as the `TILT_PORT`
argument so that the invoked command will automatically connect to
the same instance of Tilt.

Fixes #4737.

### CODE REVIEW

File: internal/tiltfile/files.go [hunk 1]
```diff
@@ -80,6 +80,19 @@ func (s *tiltfileState) execLocalCmd(t *starlark.Thread, cmd model.Cmd, logOutpu
 		c.Stderr = io.MultiWriter(stderr, logOutput)
 	}
 
+	// if Tilt was invoked with `tilt up --port=XXXXX`, local() calls to use the Tilt API will fail due to trying to
+	// connect to the default port, so explicitly populate the TILT_PORT environment variable if it isn't already
+	hasTiltPort := false
+	for _, e := range c.Env {
+		if strings.HasPrefix(e, "TILT_PORT") {
```
Comment (nicks) [inline internal/tiltfile/files.go:87]: should this be HasPrefix(e, "TILT_PORT=") ? note the '='

File: internal/tiltfile/files.go [hunk 2]
```diff
@@ -80,6 +80,19 @@ func (s *tiltfileState) execLocalCmd(t *starlark.Thread, cmd model.Cmd, logOutpu
 		c.Stderr = io.MultiWriter(stderr, logOutput)
 	}
 
+	// if Tilt was invoked with `tilt up --port=XXXXX`, local() calls to use the Tilt API will fail due to trying to
+	// connect to the default port, so explicitly populate the TILT_PORT environment variable if it isn't already
+	hasTiltPort := false
+	for _, e := range c.Env {
```
Comment (nicks) [inline internal/tiltfile/files.go:86]: it might make sense to do this in PrepareEnv with the other Env injections?
https://github.com/tilt-dev/tilt/blob/master/pkg/logger/env.go#L19

though I guess you'd have do pass webport to that function...

**Review by nicks — APPROVED** [review]

File: internal/tiltfile/files.go [hunk 3]
```diff
@@ -80,6 +80,19 @@ func (s *tiltfileState) execLocalCmd(t *starlark.Thread, cmd model.Cmd, logOutpu
...
+		if strings.HasPrefix(e, "TILT_PORT") {
+			hasTiltPort = true
+			break
+		}
+	}
+	if !hasTiltPort {
+		c.Env = append(c.Env, fmt.Sprintf("TILT_PORT=%d", s.webPort))
```
Comment (landism) [inline internal/tiltfile/files.go:93]: would it be annoying to do TILT_HOST as well?

**Review by landism — APPROVED** [review]

File: internal/tiltfile/files.go (hunk 3 above)
Comment (milas) [reply internal/tiltfile/files.go:93]: Not really - we've already got `webHost` available on the Tiltfile state (for links display).

I'll add it so that `tilt dump engine` and friends work too.

Comment (milas) [reply internal/tiltfile/files.go]: Added in f3d9caa

File: internal/tiltfile/files.go (hunk 2 above)
Comment (milas) [reply internal/tiltfile/files.go]: Yeah I thought about that but it seemed weird since that's `logger.PrepareEnv` and pretty specific to xterm type stuff.

I (_very_ briefly) looked at doing it in `Execer` and having `local()` use that but `Execer` is way more oriented to use for the BaDer for daemons and it seemed more headache/risky than it was worth. I think maybe the right thing in the future is to replace the pure `localexec.ExecCmd` with a struct that does the preparation so that it can hold state of things to inject (bonus: you also wouldn't need to pass a logger every time).

File: internal/tiltfile/files.go (hunk 1 above)
Comment (milas) [reply internal/tiltfile/files.go]: Good call - tweaked that when making it more generic to handle `TILT_HOST` so it'll need to be `${key}=` in f3d9caa
