### PR TITLE
engine: don't reparse yaml on every KA/KD upsert

### LINKED ISSUE #5837: Performance issues when reconciling very large CRD manifests
I am currently running into a significant performance issue when applying large CRD manifests to a cluster using tilt. I have spent a little while debugging tilt's internals to pinpoint the issue, and here are my findings:
1. On every iteration of the Store's action loop, the upper reducer function processes a `KubernetesDiscoveryUpsertAction` dispatched by the `kubernetesdiscovery` reconciler.
2. The handler for this action will eventually call `k8sconv.NewKubernetesApplyFilter` which parses the yaml from `KubernetesApplyStatus.ResultYAML`. In my case, one of the large CRD manifests weighs in at over 6 MB. This manifest takes a long time to parse (couple seconds). Parsing YAML is the main contributor to the performance issues, as far as I can tell.
3. The frequency at which `KubernetesDiscoveryUpsertAction`s are dispatched will overwhelm the event queue. Additionally, the following code in Store ends up creating a lot of goroutines, increasing lock contention which causes additional slowdowns (though this seems to not be the main problem):
```go
func (s *Store) Dispatch(action Action) {
	s.actionQueue.add(action)
	go s.drainActions()
}
```

### Steps to Reproduce

1. Obtain a large CRD manifest (e.g. prometheus operator)
2. Apply it using `k8s_yaml`

#### `tilt doctor` Output

```
$ tilt doctor
Tilt: v0.30.1-dev, built 2022-06-01
System: linux-amd64
---
Docker
- Host: unix:///var/run/docker.sock
- Server Version: 20.10.16
- API Version: 1.41
- Builder: 2
---
Kubernetes
- Env: unknown
- Context: kubernetes-admin@kubernetes
- Cluster Name: opni-testing
- Namespace: default
- Container Runtime: containerd
- Version: v1.24.1
- Cluster Local Registry: none
---
Thanks for seeing the Tilt Doctor!
Please send the info above when filing bug reports. 💗

The info below helps us understand how you're using Tilt so we can improve,
but is not required to ask for help.
---
Analytics Settings
--> (These results reflect your personal opt in/out status and may be overridden by an `analytics_settings` call in your Tiltfile)
- User Mode: opt-in
- Machine: 794145422d20ad7eae9c13868585b957
- Repo: 30P//3m6QZhY3W8urCRPnQ==
```

### Additional Info
Here is a pprof cpu profile from running `tilt up` that may be helpful: [profile.gz](https://github.com/tilt-dev/tilt/files/8819124/profile.gz)
Try viewing it with `go tool pprof -web -show='github\.com\/tilt-dev\.*' profile`.

### PR DESCRIPTION
**Pull request by landism**
Fixes #5837

I described a few other potential solutions in a comment on the issue. This is probably my least favorite of them, but it's nice and cheap. I'm happy to entertain alternatives.

### CODE REVIEW

File: internal/store/kubernetesdiscoverys/reducers.go [hunk 1]
```diff
@@ -50,10 +67,11 @@ func RefreshKubernetesResource(state *store.EngineState, name string) {
 	}
 
 	d := state.KubernetesDiscoverys[name]
-	r, err := k8sconv.NewKubernetesResource(d, aStatus)
+	filter, err := filterForResource(state, name)
```
Comment (nicks) [inline internal/store/kubernetesdiscoverys/reducers.go:70]: would it work to do an apicmp.DeepEqual() on both the discovery and the apply, and skip the whole refresh branch if they're the same?

this is supposed to be idempotent.

Comment (landism) [reply internal/store/kubernetesdiscoverys/reducers.go:70]: In the problematic code path, [we already do](https://github.com/tilt-dev/tilt/blob/0f1dcaa3eec0e99e3b23883d6ff0546b1fc147ea/internal/store/kubernetesdiscoverys/reducers.go#L27-L32).

My (unverified) understanding of the issue is that there are a lot of pod status changes in the cluster, which generate KD status changes, which generate KD upsert actions, and since the KD status has changed, they generate calls to RefreshKubernetesResource, which reparse yaml that hasn't changed. I'll see if the user can confirm this.

**Review by nicks — APPROVED** [review]
ah, ok, that makes sense

**Review by milas — APPROVED** [review]
Maybe your least favorite of the options, but all-in-all a pretty solid fix given the constraints IMO 👏
