### PR TITLE
tiltfile: don't check enabled resources when loading failed

### LINKED ISSUE #5467: If the Tiltfile fails when running with args, the actual error is replaced "resources could not be found"
### Steps to Reproduce
```
echo asdf > Tiltfile
tilt up --stream foo
```

### Expected Behavior
an error saying "asdf" is undefined

### Current Behavior
```
Initial Build • (Tiltfile)
Loading Tiltfile at: /private/tmp/failure/Tiltfile
ERROR: You specified some resources that could not be found: "foo"
Is this a typo? Existing resources in Tiltfile:
```

### Context
The bug is [here](https://github.com/tilt-dev/tilt/pull/5418/files#diff-5dd3a4078ee8561a8218564544e9edb87c9269ddc254bd0da9fbaa80425f9070R218-R221), introduced in v0.24.0

### PR DESCRIPTION
**Pull request by landism**
fixes #5467

### CODE REVIEW

File: internal/tiltfile/tiltfile.go [hunk 1]
```diff
@@ -216,12 +216,9 @@ func (tfl tiltfileLoader) Load(ctx context.Context, tf *corev1alpha1.Tiltfile) T
 	tlr.UpdateSettings = us
 
 	configSettings, _ := config.GetState(result)
-	enabledManifests, err := configSettings.EnabledResources(tf, manifests)
-	if err != nil {
-		tlr.Error = err
-		return tlr
+	if tlr.Error == nil {
+		tlr.EnabledManifests, tlr.Error = configSettings.EnabledResources(tf, manifests)
```
Comment (landism) [inline internal/tiltfile/tiltfile.go:220]: `EnabledManifests` is ignored downstream when `tlr.Error` is non-nil anyway

**Review by nicks — APPROVED** [review]
LGTM

if you want to do a release for this, we'll either need to do v0.25 (for the extensions stuff) or do a cherrypick branch for v0.24.1
